services:
  app:
    extends:
      file: .docker/docker-compose.app.yaml
      service: app
  client-1:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-1
  client-2:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-2
  client-3:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-3
  client-4:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-4
  client-5:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-5
  client-6:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-6
  client-7:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-7
  client-8:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-8
  client-9:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-9
  client-10:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-10
  client-11:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-11
  client-12:
    deploy:
      replicas: 1
    extends:
      file: .docker/docker-compose.client.yaml
      service: client-12
  prometheus:
    extends:
      file: .docker/docker-compose.metrics.yaml
      service: prometheus
  grafana:
    extends:
      file: .docker/docker-compose.metrics.yaml
      service: grafana
  # ollama:
  #   extends:
  #     file: .docker/docker-compose.ollama.mac.yaml
  #     service: ollama
  # open-webui:
  #   extends:
  #     file: .docker/docker-compose.ollama.mac.yaml
  #     service: open-webui
  face-emotion-api:
    extends:
      file: .docker/docker-compose.llm.yaml
      service: face-emotion-api
  toxiproxy:
    extends:
      file: .docker/docker-compose.toxiproxy.yml
      service: toxiproxy
  toxiproxy-ui:
    extends:
      file: .docker/docker-compose.toxiproxy.yml
      service: toxiproxy-ui
  toxiproxy-config:
    extends:
      file: .docker/docker-compose.toxiproxy.yml
      service: toxiproxy-config
