services:
  app:
    extends:
      file: .docker/docker-compose.app.yaml
      service: app
  client:
    extends:
      file: .docker/docker-compose.app.yaml
      service: client
  prometheus:
    extends:
      file: .docker/docker-compose.metrics.yaml
      service: prometheus
  grafana:
    extends:
      file: .docker/docker-compose.metrics.yaml
      service: grafana
  # ollama:
  #   extends:
  #     file: .docker/docker-compose.ollama.mac.yaml
  #     service: ollama
  # open-webui:
  #   extends:
  #     file: .docker/docker-compose.ollama.mac.yaml
  #     service: open-webui
  face-emotion-api:
    extends:
      file: .docker/docker-compose.llm.yaml
      service: face-emotion-api
