services:
  app:
    container_name: app
    image: mihaitatinta/http3-playground:0.0.1
    ports:
      - 443:8443
      - 80:8080
    environment:
      - DEBUG=false
      - SERVER_PORT=8080
      - SERVER_SSL_ENABLED=false
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=llava-phi3
      - OLLAMA_PROMPT_FILE=file:///home/www/assets/prompt.md
      - SPRING_WEB_RESOURCES_STATIC_LOCATIONS=file:///home/www
      - SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_CERTIFICATE=file:///home/certs/fullchain.pem
      - SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_PRIVATE_KEY=file:///home/certs/privkey.pem
    volumes:
      - ../www:/home/www
      - ./certs:/home/certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
