services:
  ollama:
    ports:
      - ${OLLAMA_WEBAPI_PORT-11434}:11434
    volumes:
      - ./ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: unless-stopped
    image: ollama/ollama:${OLLAMA_DOCKER_TAG-latest}
    environment:
      - OLLAMA_NUM_PARALLEL=2
      - OLLAMA_MAX_LOADED_MODELS=2
      - OLLAMA_MAX_QUEUE=10
#    deploy:
#      resources:
#        reservations:
#          devices:
#            - driver: ${OLLAMA_GPU_DRIVER-nvidia}
#              count: ${OLLAMA_GPU_COUNT-1}
#              capabilities:
#                - gpu

  open-webui:
#    build:
#      context: .
#      args:
#        OLLAMA_BASE_URL: "/ollama"
#      dockerfile: Dockerfile
    image: ghcr.io/ollama-webui/ollama-webui:main
    container_name: open-webui
    volumes:
      - ./open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - USE_OLLAMA_DOCKER=true
      - OLLAMA_BASE_URL=http://ollama:11434
#      - OLLAMA_BASE_URLS=http://ollama-one:11434;http://ollama-two:11434
      - WEBUI_SECRET_KEY=
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
