services:
  app:
    container_name: app
    image: "amazoncorretto:21.0.3-al2023-headless"
    platform: ${DOCKER_PLATFORM}
    ports:
      - 443:8443
      - 80:8080
    command: bash -c "java -XX:MinRAMPercentage=50.0 -XX:MaxRAMPercentage=90.0 -XshowSettings:vm -XX:+HeapDumpOnOutOfMemoryError -XX:HeapDumpPath=/home/jfr/heap_dump.hprof -XX:StartFlightRecording=delay=10s,maxsize=1g,disk=true,dumponexit=true,filename=/home/jfr/latest.jfr -jar /home/app/demo-0.0.1-SNAPSHOT.jar --websocket.input.dir=/home/input --websocket.target.port=8080 --websocket.target.host=app"
    environment:
      - DEBUG=false
#      - SERVER_PORT=8080
#      - SERVER_SSL_ENABLED=false
      - SERVER_PORT=8443
      - SERVER_SSL_ENABLED=true
      - SERVER_SSL_BUNDLE=server
      - SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_CERTIFICATE=file:///home/certs/fullchain.pem
      - SPRING_SSL_BUNDLE_PEM_SERVER_KEYSTORE_PRIVATE_KEY=file:///home/certs/privkey.pem
      - LLM_HOST=face-emotion-api
      - OLLAMA_ENABLED=true
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434
      - OLLAMA_MODEL=phi3
      - OLLAMA_PROMPT_FILE=file:///home/www/assets/prompt.md
      - SPRING_WEB_RESOURCES_STATIC_LOCATIONS=file:///home/www
    volumes:
      - ../www:/home/www
      - ../target:/home/app
      - ../target:/home/jfr
      - ./certs:/home/certs
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 1G
        reservations:
          cpus: "4"
          memory: 1G
