services:
  face-emotion-api:
    container_name: face-emotion-api
    platform: ${DOCKER_PLATFORM}
    build: ./local-llm
    ports:
      - "8000:8000"
    volumes:
      - ./local-llm/.cache:/.cache

    deploy:
      resources:
        limits:
          cpus: "8"
          memory: 8G
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities:
                - gpu
